const Menu=[
    {
        id:1,
        Category:"Summer",
        Name:"Mango",
        price:200,
        img:"images/mango.jpeg",
        description:"sjdafg"
    },
    {
        id:2,
        Category:"Rainy",
        Name:"Banana",
        price:100,
        img:"images/banana.jpeg",
        description:"sjdafg"
    },
    {
        id:3,
        Category:"Winter",
        Name:"Kiwi",
        price:150,
        img:"images/kiwi.jpeg",
        description:"sjdafg"
    },
    {
        id:4,
        Category:"Spring",
        Name:"Grapes",
        price:100,
        img:"images/grapes.jpeg",
        description:"sjdafg"
    },
    {
        id:5,
        Category:"Autumn",
        Name:"Apple",
        price:300,
        img:"images/apple.jpeg",
        description:"sjdafg"
    },
    {
        id:6,
        Category:"Summer",
        Name:"WaterMelon",
        price:250,
        img:"images/watermelon.jpeg",
        description:"sjdafg"
    },
    {
        id:10,
        Category:"Summer",
        Name:"Mango",
        price:200,
        img:"images/mango.jpeg",
        description:"sjdafg"
    },
    {
        id:10,
        Category:"Summer",
        Name:"Mango",
        price:200,
        img:"images/mango.jpeg",
        description:"sjdafg"
    },

]
export default Menu;